INSERT INTO pokemon (id, url, name, first_type, second_type) VALUES
    (1L, '/assets/pokemons/Bulbasaur.png','Bulbasaur', 3, 7),
    (2L, '/assets/pokemons/Ivysaur.png', 'Ivysaur', 3, 7),
    (3L, '/assets/pokemons/Venusaur.png', 'Venusaur', 3, 7),
    (4L, '/assets/pokemons/Charmander.png', 'Charmander', 1, 18),
    (5L, '/assets/pokemons/Charmeleon.png', 'Charmeleon', 1, 18),
    (6L, '/assets/pokemons/Charizard.png', 'Charizard', 1, 9),
    (7L, '/assets/pokemons/Squirtle.png', 'Squirtle', 2, 18),
    (8L, '/assets/pokemons/Wartortle.png', 'Watortle', 2, 18),
    (9L, '/assets/pokemons/Blastoise.png', 'Blastoise', 2, 18),
    (10L, '/assets/pokemons/Caterpie.png', 'Caterpie', 11, 18),
    (11L, '/assets/pokemons/Metapod.png', 'Metapod', 11, 18),
    (12L, '/assets/pokemons/Butterfree.webp', 'Butterfree', 11, 9),
    (13L, '/assets/pokemons/Weedle.png', 'Weedle', 11, 7),
    (14L, '/assets/pokemons/Kakuna.png', 'Kakuna', 11, 7),
    (15L, '/assets/pokemons/Beedrill.png', 'Beedrill', 11, 7),
    (16L, '/assets/pokemons/Pidgey.png', 'Pidgey', 0, 9),
    (17L, '/assets/pokemons/Pidgeotto.png', 'Pidgeotto', 0, 9),
    (18L, '/assets/pokemons/Pidgeot.png', 'Pidgeot', 0, 9),
    (19L, '/assets/pokemons/Rattata.png', 'Rattata', 0, 18),
    (20L, '/assets/pokemons/Raticate.png', 'Raticate', 0, 18),
    (21L, '/assets/pokemons/Spearow.png', 'Spearow', 0, 9),
    (22L, '/assets/pokemons/Fearow.png', 'Fearow', 0, 9),
    (23L, '/assets/pokemons/Ekans.png', 'Ekans', 7, 18),
    (24L, '/assets/pokemons/Arbok.png', 'Arbok', 7, 18),
    (25L, '/assets/pokemons/Pikachu.png', 'Pikachu', 4, 18),
    (26L, '/assets/pokemons/Raichu.webp', 'Raichu', 4, 18),
    (27L, '/assets/pokemons/Sandshrew.png', 'Sandshrew', 8, 18),
    (28L, '/assets/pokemons/Sandslash.png', 'Sandslash', 8, 18),
    (29L, '/assets/pokemons/Nidoran.png', 'Nidoran♀', 7, 18),
    (30L, '/assets/pokemons/Nidorina.png', 'Nidorina', 7, 18),
    (31L, '/assets/pokemons/Nidoqueen.png', 'Nidoqueen', 7, 8),
    (32L, '/assets/pokemons/NidoranM.png', 'Nidoran♂', 7, 18),
    (33L, '/assets/pokemons/Nidorino.png', 'Nidorino', 7, 18),
    (34L, '/assets/pokemons/Nidoking.png', 'Nidoking', 7, 8),
    (35L, '/assets/pokemons/Clefairy.png', 'Clefairy', 17, 18 ),
    (36L, '/assets/pokemons/Clefable.png', 'Clefable', 17, 18),
    (37L, 'https://archives.bulbagarden.net/media/upload/thumb/6/60/037Vulpix.png/375px-037Vulpix.png', 'Vulpix', 1, 18),
    (38L, 'https://archives.bulbagarden.net/media/upload/thumb/0/05/038Ninetales.png/375px-038Ninetales.png', 'Ninetales', 1, 18),
    (39L, 'https://archives.bulbagarden.net/media/upload/thumb/3/3e/039Jigglypuff.png/375px-039Jigglypuff.png', 'Jigglypuff', 0, 17),
    (40L, 'https://archives.bulbagarden.net/media/upload/thumb/9/92/040Wigglytuff.png/375px-040Wigglytuff.png', 'Wigglytuff', 0, 17),
    (41L, 'https://archives.bulbagarden.net/media/upload/thumb/d/da/041Zubat.png/375px-041Zubat.png', 'Zubat', 7, 9),
    (42L, 'https://archives.bulbagarden.net/media/upload/thumb/0/0c/042Golbat.png/375px-042Golbat.png', 'Golbat', 7, 9),
    (43L, 'https://archives.bulbagarden.net/media/upload/thumb/4/43/043Oddish.png/375px-043Oddish.png', 'Oddish', 3, 7),
    (44L, 'https://archives.bulbagarden.net/media/upload/thumb/2/2a/044Gloom.png/375px-044Gloom.png', 'Gloom', 3, 7),
    (45L, 'https://archives.bulbagarden.net/media/upload/thumb/6/6a/045Vileplume.png/375px-045Vileplume.png', 'Vileplume', 3, 7),
    (46L, 'https://archives.bulbagarden.net/media/upload/thumb/d/d4/046Paras.png/375px-046Paras.png', 'Paras', 11, 3),
    (47L, 'https://archives.bulbagarden.net/media/upload/thumb/8/80/047Parasect.png/375px-047Parasect.png', 'Parasect', 11, 3),
    (48L, 'https://archives.bulbagarden.net/media/upload/thumb/a/ad/048Venonat.png/375px-048Venonat.png', 'Venonat', 11, 7),
    (49L, 'https://archives.bulbagarden.net/media/upload/thumb/d/d3/049Venomoth.png/375px-049Venomoth.png', 'Venomoth', 11, 7),
    (50L, 'https://archives.bulbagarden.net/media/upload/thumb/3/31/050Diglett.png/375px-050Diglett.png', 'Diglett', 8, 18),
    (51L, 'https://archives.bulbagarden.net/media/upload/thumb/e/e5/051Dugtrio.png/375px-051Dugtrio.png', 'Dugtrio', 8, 18),
    (52L, 'https://archives.bulbagarden.net/media/upload/thumb/d/d6/052Meowth.png/375px-052Meowth.png', 'Meowth', 0, 18),
    (53L, 'https://archives.bulbagarden.net/media/upload/thumb/1/13/053Persian.png/375px-053Persian.png', 'Persian', 0, 18),
    (54L, 'https://archives.bulbagarden.net/media/upload/thumb/5/53/054Psyduck.png/375px-054Psyduck.png', 'Psyduck', 2, 18),
    (55L, 'https://archives.bulbagarden.net/media/upload/thumb/f/fe/055Golduck.png/375px-055Golduck.png', 'Golduck', 2, 18 ),
    (56L, 'https://archives.bulbagarden.net/media/upload/thumb/4/41/056Mankey.png/375px-056Mankey.png', 'Mankey', 6, 18),
    (57L, 'https://archives.bulbagarden.net/media/upload/thumb/9/9a/057Primeape.png/375px-057Primeape.png', 'Primeape', 6, 18),
    (58L, 'https://archives.bulbagarden.net/media/upload/thumb/3/3d/058Growlithe.png/375px-058Growlithe.png', 'Growlithe', 1, 18),
    (59L, 'https://archives.bulbagarden.net/media/upload/thumb/b/b8/059Arcanine.png/375px-059Arcanine.png', 'Arcanine', 1, 18),
    (60L, 'https://archives.bulbagarden.net/media/upload/thumb/4/49/060Poliwag.png/375px-060Poliwag.png', 'Poliwag', 2, 18),
    (61L, 'https://archives.bulbagarden.net/media/upload/thumb/a/a9/061Poliwhirl.png/375px-061Poliwhirl.png', 'Poliwhirl', 2, 18),
    (62L, 'https://archives.bulbagarden.net/media/upload/thumb/2/2d/062Poliwrath.png/375px-062Poliwrath.png', 'Poliwrath', 2, 6),
    (63L, 'https://archives.bulbagarden.net/media/upload/thumb/6/62/063Abra.png/375px-063Abra.png', 'Abra', 10, 18),
    (64L, 'https://archives.bulbagarden.net/media/upload/thumb/9/97/064Kadabra.png/375px-064Kadabra.png', 'Kadabra', 10, 18),
    (65L, 'https://archives.bulbagarden.net/media/upload/thumb/c/cc/065Alakazam.png/375px-065Alakazam.png', 'Alakazam', 10, 18),
    (66L, 'https://archives.bulbagarden.net/media/upload/thumb/8/85/066Machop.png/375px-066Machop.png', 'Machop', 6, 18),
    (67L, 'https://archives.bulbagarden.net/media/upload/thumb/8/8e/067Machoke.png/375px-067Machoke.png', 'Machoke', 6, 18),
    (68L, 'https://archives.bulbagarden.net/media/upload/thumb/8/8f/068Machamp.png/375px-068Machamp.png', 'Machamp', 6, 18),
    (69L, 'https://archives.bulbagarden.net/media/upload/thumb/a/a2/069Bellsprout.png/375px-069Bellsprout.png', 'Bellsprout', 3, 7),
    (70L, 'https://archives.bulbagarden.net/media/upload/thumb/9/9f/070Weepinbell.png/375px-070Weepinbell.png', 'Weepinbell', 3, 7),
    (71L, 'https://archives.bulbagarden.net/media/upload/thumb/b/be/071Victreebel.png/375px-071Victreebel.png', 'Victreebell', 3, 7),
    (72L, 'https://archives.bulbagarden.net/media/upload/thumb/4/4e/072Tentacool.png/375px-072Tentacool.png', 'Tentacool', 2, 7),
    (73L, 'https://archives.bulbagarden.net/media/upload/thumb/f/f6/073Tentacruel.png/375px-073Tentacruel.png', 'Tentacruel', 2, 7),
    (74L, 'https://archives.bulbagarden.net/media/upload/thumb/9/98/074Geodude.png/375px-074Geodude.png', 'Geodude', 12, 8),
    (75L, 'https://archives.bulbagarden.net/media/upload/thumb/7/75/075Graveler.png/375px-075Graveler.png', 'Graveler', 12, 8),
    (76L, 'https://archives.bulbagarden.net/media/upload/thumb/f/f2/076Golem.png/375px-076Golem.png', 'Golem', 12, 8),
    (77L, 'https://archives.bulbagarden.net/media/upload/thumb/3/3b/077Ponyta.png/375px-077Ponyta.png', 'Ponyta', 1, 18),
    (78L, 'https://archives.bulbagarden.net/media/upload/thumb/3/3f/078Rapidash.png/375px-078Rapidash.png', 'Rapidash', 1, 18),
    (79L, 'https://archives.bulbagarden.net/media/upload/thumb/7/70/079Slowpoke.png/375px-079Slowpoke.png', 'Slowpoke', 2, 10),
    (80L, 'https://archives.bulbagarden.net/media/upload/thumb/8/80/080Slowbro.png/375px-080Slowbro.png', 'Slowbro', 2, 10),
    (81L, 'https://archives.bulbagarden.net/media/upload/thumb/6/6c/081Magnemite.png/375px-081Magnemite.png', 'Magnemite', 4, 16),
    (82L, 'https://archives.bulbagarden.net/media/upload/thumb/7/72/082Magneton.png/375px-082Magneton.png', 'Magnetom', 4, 16),
    (83L, 'https://archives.bulbagarden.net/media/upload/thumb/f/f8/083Farfetch%27d.png/375px-083Farfetch%27d.png', 'Farfetch''d', 0, 9),
    (84L, 'https://archives.bulbagarden.net/media/upload/thumb/5/54/084Doduo.png/375px-084Doduo.png', 'Doduo', 0, 9),
    (85L, 'https://archives.bulbagarden.net/media/upload/thumb/9/93/085Dodrio.png/375px-085Dodrio.png', 'Dodrio', 0, 9),
    (86L, 'https://archives.bulbagarden.net/media/upload/thumb/1/1f/086Seel.png/375px-086Seel.png', 'Seel', 2, 18),
    (87L, 'https://archives.bulbagarden.net/media/upload/thumb/c/c7/087Dewgong.png/375px-087Dewgong.png', 'Dewgong', 2, 5),
    (88L, 'https://archives.bulbagarden.net/media/upload/thumb/a/a0/088Grimer.png/250px-088Grimer.png', 'Grimer', 7, 18),
    (89L, 'https://archives.bulbagarden.net/media/upload/thumb/7/7c/089Muk.png/250px-089Muk.png', 'Muk', 7, 18),
    (90L, 'https://archives.bulbagarden.net/media/upload/thumb/4/40/090Shellder.png/250px-090Shellder.png', 'Shellder', 2, 18),
    (91L, 'https://archives.bulbagarden.net/media/upload/thumb/1/1d/091Cloyster.png/250px-091Cloyster.png', 'Cloyster', 2, 5),
    (92L, 'https://archives.bulbagarden.net/media/upload/thumb/c/ca/092Gastly.png/250px-092Gastly.png', 'Gastly', 13, 7),
    (93L, 'https://archives.bulbagarden.net/media/upload/thumb/6/62/093Haunter.png/250px-093Haunter.png', 'Haunter', 13, 7),
    (94L, 'https://archives.bulbagarden.net/media/upload/thumb/c/c6/094Gengar.png/250px-094Gengar.png', 'Gengar', 13, 7),
    (95L, 'https://archives.bulbagarden.net/media/upload/thumb/9/9a/095Onix.png/250px-095Onix.png', 'Onix', 12, 8),
    (96L, 'https://archives.bulbagarden.net/media/upload/thumb/3/3e/096Drowzee.png/250px-096Drowzee.png', 'Drowzee', 10, 18),
    (97L, 'https://archives.bulbagarden.net/media/upload/thumb/0/0a/097Hypno.png/250px-097Hypno.png', 'Hypno', 10, 18),
    (98L, 'https://archives.bulbagarden.net/media/upload/thumb/a/a7/098Krabby.png/250px-098Krabby.png', 'Krabby', 2, 18),
    (99L, 'https://archives.bulbagarden.net/media/upload/thumb/7/71/099Kingler.png/250px-099Kingler.png', 'Kingler', 2, 18),
    (100L, 'https://archives.bulbagarden.net/media/upload/thumb/d/da/100Voltorb.png/250px-100Voltorb.png', 'Voltorb', 4, 18),
    (101L, 'https://archives.bulbagarden.net/media/upload/thumb/8/84/101Electrode.png/250px-101Electrode.png', 'Electrode', 4, 18),
    (102L, 'https://archives.bulbagarden.net/media/upload/thumb/a/af/102Exeggcute.png/250px-102Exeggcute.png', 'Exeggcute', 3, 10),
    (103L, 'https://archives.bulbagarden.net/media/upload/thumb/2/24/103Exeggutor.png/250px-103Exeggutor.png', 'Exeggutor', 3, 10),
    (104L, 'https://archives.bulbagarden.net/media/upload/thumb/2/2a/104Cubone.png/250px-104Cubone.png', 'Cubone', 8, 18),
    (105L, 'https://archives.bulbagarden.net/media/upload/thumb/9/98/105Marowak.png/250px-105Marowak.png', 'Marowak', 8, 18),
    (106L, 'https://archives.bulbagarden.net/media/upload/thumb/3/32/106Hitmonlee.png/250px-106Hitmonlee.png', 'Hitmonlee', 6, 18),
    (107L, 'https://archives.bulbagarden.net/media/upload/thumb/a/a3/107Hitmonchan.png/250px-107Hitmonchan.png', 'Hitmonchan', 6, 18),
    (108L, 'https://archives.bulbagarden.net/media/upload/thumb/0/00/108Lickitung.png/250px-108Lickitung.png', 'Lickitung', 0, 18),
    (109L, 'https://archives.bulbagarden.net/media/upload/thumb/1/17/109Koffing.png/250px-109Koffing.png', 'Koffing', 7, 18),
    (110L, 'https://archives.bulbagarden.net/media/upload/thumb/4/42/110Weezing.png/250px-110Weezing.png', 'Weezing', 7, 18),
    (111L, 'https://archives.bulbagarden.net/media/upload/thumb/9/9b/111Rhyhorn.png/250px-111Rhyhorn.png', 'Rhyhorn', 8, 12),
    (112L, 'https://archives.bulbagarden.net/media/upload/thumb/4/47/112Rhydon.png/250px-112Rhydon.png', 'Rhydon', 8, 12),
    (113L, 'https://archives.bulbagarden.net/media/upload/thumb/c/cd/113Chansey.png/250px-113Chansey.png', 'Chansey', 0, 18),
    (114L, 'https://archives.bulbagarden.net/media/upload/thumb/3/3e/114Tangela.png/250px-114Tangela.png', 'Tangela', 3, 18),
    (115L, 'https://archives.bulbagarden.net/media/upload/thumb/4/4e/115Kangaskhan.png/250px-115Kangaskhan.png', 'Kangaskhan', 0, 18),
    (116L, 'https://archives.bulbagarden.net/media/upload/thumb/5/5a/116Horsea.png/250px-116Horsea.png', 'Horsea', 2, 18),
    (117L, 'https://archives.bulbagarden.net/media/upload/thumb/2/26/117Seadra.png/250px-117Seadra.png', 'Seadra', 2, 18),
    (118L, 'https://archives.bulbagarden.net/media/upload/thumb/7/7b/118Goldeen.png/250px-118Goldeen.png', 'Goldeen', 2, 18),
    (119L, 'https://archives.bulbagarden.net/media/upload/thumb/6/6a/119Seaking.png/250px-119Seaking.png', 'Seaking', 2, 18),
    (120L, 'https://archives.bulbagarden.net/media/upload/thumb/4/4f/120Staryu.png/250px-120Staryu.png', 'Staryu', 2, 18),
    (121L, 'https://archives.bulbagarden.net/media/upload/thumb/c/cd/121Starmie.png/250px-121Starmie.png', 'Starmie', 2, 10),
    (122L, 'https://archives.bulbagarden.net/media/upload/thumb/e/ec/122Mr._Mime.png/250px-122Mr._Mime.png', 'Mr. Mime', 10, 17),
    (123L, 'https://archives.bulbagarden.net/media/upload/thumb/b/ba/123Scyther.png/250px-123Scyther.png', 'Scyther', 11, 9),
    (124L, 'https://archives.bulbagarden.net/media/upload/thumb/7/7c/124Jynx.png/250px-124Jynx.png', 'Jynx', 5, 10),
    (125L, 'https://archives.bulbagarden.net/media/upload/thumb/d/de/125Electabuzz.png/250px-125Electabuzz.png', 'Electabuzz', 4, 18),
    (126L, 'https://archives.bulbagarden.net/media/upload/thumb/8/8c/126Magmar.png/250px-126Magmar.png', 'Magmar', 1, 18),
    (127L, 'https://archives.bulbagarden.net/media/upload/thumb/7/71/127Pinsir.png/250px-127Pinsir.png', 'Pinsir', 11, 18),
    (128L, 'https://archives.bulbagarden.net/media/upload/thumb/b/b8/128Tauros.png/250px-128Tauros.png', 'Tauros', 0, 18),
    (129L, 'https://archives.bulbagarden.net/media/upload/thumb/0/02/129Magikarp.png/250px-129Magikarp.png', 'Magikarp', 2, 18),
    (130L, 'https://archives.bulbagarden.net/media/upload/thumb/4/41/130Gyarados.png/40px-130Gyarados.png', 'Gyarados', 2, 9),
    (131L, 'https://archives.bulbagarden.net/media/upload/thumb/a/ab/131Lapras.png/250px-131Lapras.png', 'Lapras', 2, 5),
    (132L, 'https://archives.bulbagarden.net/media/upload/thumb/3/36/132Ditto.png/250px-132Ditto.png', 'Ditto', 0, 18),
    (133L, 'https://archives.bulbagarden.net/media/upload/thumb/e/e2/133Eevee.png/250px-133Eevee.png', 'Eevee', 0, 18),
    (134L, 'https://archives.bulbagarden.net/media/upload/thumb/f/fd/134Vaporeon.png/250px-134Vaporeon.png', 'Vaporeon', 2, 18),
    (135L, 'https://archives.bulbagarden.net/media/upload/thumb/b/bb/135Jolteon.png/250px-135Jolteon.png', 'Jolteon', 4, 18),
    (136L, 'https://archives.bulbagarden.net/media/upload/thumb/d/dd/136Flareon.png/250px-136Flareon.png', 'Flareon', 1, 18),
    (137L, 'https://archives.bulbagarden.net/media/upload/thumb/6/6b/137Porygon.png/250px-137Porygon.png', 'Porygon', 0, 18),
    (138L, '/assets/pokemons/Omanyte.png', 'Omanyte', 12, 2),
    (139L, '/assets/pokemons/Omastar.png', 'Omastar', 12, 2),
    (140L, '/assets/pokemons/Kabuto.png', 'Kabuto', 12, 2),
    (141L, '/assets/pokemons/Kabutops.png', 'Kabutops', 12, 2),
    (142L, '/assets/pokemons/Aerodactyl.png', 'Aerodactyl', 12, 9),
    (143L, '/assets/pokemons/Snorlax.webp', 'Snorlax', 0, 18),
    (144L, '/assets/pokemons/Articuno.png', 'Articuno', 5, 9),
    (145L, '/assets/pokemons/Zapdos.png', 'Zapdos', 4, 9),
    (146L, '/assets/pokemons/Moltres.png', 'Moltres', 1, 9),
    (147L, '/assets/pokemons/Dratini.png', 'Dratini', 14, 18),
    (148L, '/assets/pokemons/Dragonair.png', 'Dragonair', 14, 18),
    (149l, '/assets/pokemons/Dragonite.png', 'Dragonite', 14, 9),
    (150L, '/assets/pokemons/Mewtwo.png', 'Mewtwo', 10, 18),
    (151L, '/assets/pokemons/Mew.png', 'Mew', 10, 18);

INSERT INTO area (id, name, pokemons, url) VALUES
    (1L, 'Pallet Town', 'magikarp poliwag goldeen tentacool staryu bulbasaur charmander squirtle pikachu', '/assets/locations/Pallet_Town_HGSS.png'),
    (2L, 'Route 1', 'pidgey rattata', '/assets/locations/Route_1_HGSS.png'),
    (3L, 'Viridian City', ' magikarp poliwag goldeen tentacool', '/assets/locations/Viridian_City_HGSS.png'),
    (4L, 'Route 2', 'rattata pidgey weedle caterpie nidoran(f) nidoran(M) mr.Mime', '/assets/locations/Route_2_HGSS.png' ),
    (5L, 'Viridian Forest', 'weedle caterpie kakuna metapod pikachu pidgey pidgeotto', '/assets/locations/Forest_HGSS.png'),
    (6L, 'Digletts cave', ' diglett dugtrio', '/assets/locations/Diglett_Cave_HGSS.png'),
    (7L, 'Route 3', 'pidgey spearow rattata sandshrew mankey jigglypuff', '/assets/locations/Route_3_HGSS.png'),
    (8L, 'Mt. Moon', 'zubat geodude paras clefairy sandshrew', '/assets/locations/Mt_Moon_1F_HGSS.png'),
    (9L, 'Route 4', 'rattata Spearow ekans sandshrew mankey magikarp', '/assets/locations/Route_4_HGSS.png'),
    (10L, 'Cerulean Cave', 'golbat magneton hypno arbok sandslash vanomoth dodrio parasect kadabra raichu ditto graveler gloom weepinbell electrode marowak rhydon wigglypuff chansey rhyhorn lickitung magikarp poliwag slowbro krabby seadra seaking mewtwo', '/assets/locations/Cerulean_Cave_1F_HGSS.png'),
    (11L, 'Cerulean City', 'magikarp poliwag goldeen psyduck krabby seaking bulbasaur jynx', '/assets/locations/Cerulean_City_HGSS.png'),
    (12L, 'Route 5', 'oddish bellsprout pidgey rattata mankey meowth abra jigglypuff pidgeotto nidoran(f) machoke', '/assets/locations/Route_5_HGSS.png'),
    (13L, 'Saffron City', 'hitmonlee hitmonchan', '/assets/locations/Saffron_City_HGSS.png'),
    (14L, 'Silph Co', 'lapras', '/assets/locations/Silph_Co_1F_HGSS.png'),
    (15L, 'Route 6', 'pidgey pidgeotto rattata jigglypuff oddish meowth mankey bellsprout abra psyduck golduck magikarp poliwag goldeen shellder krabby', '/assets/locations/Route_6_HGSS.png'),
    (16L, 'Vermillion City', 'magikarp poliwag goldeen shellder krabby tentacool horsea staryu squirtle farfetch''d', '/assets/locations/Vermilion_City_HGSS.png'),
    (17L, 'Route 7', 'pidgey pidgeotto rattata jigglypuff oddish bellsprout mankey meowth growlithe vulpix abra', '/assets/locations/Route_7_HGSS.png'),
    (18L, 'Celadon City', 'magikarp poliwag goldeen poliwhirl slowpoke eevee', '/assets/locations/Celadon_City_HGSS.png'),
    (19L, 'Route 8', 'pidgey pidgeotto rattata ekans sandshrew vulpix jigglypuff mankey meowth growlithe abra kadabra', '/assets/locations/Route_8_HGSS.png'),
    (20L, 'Pokemon Tower', 'gastly cubone haunter', '/assets/locations/Lavender_Radio_Tower_HGSS.png'),
    (21L, 'Route 10', 'voltorb Spearow ekans sandshrew magnemite rattata nidoran(m) nidoran(f) raticate machop magikarp poliwag goldeen poliwhirl slowpoke krabby horsea kingler', '/assets/locations/Route_10_HGSS.png'),
    (22L, 'Rock Tunnel', 'zubat geodude machop onix', '/assets/locations/Rock_Tunnel_1_HGSS.png'),
    (23L, 'Power Plant', 'voltorb pikachu magnemite magneton electabuzz raichu grimer muk electrode zapdos', '/assets/locations/Power_Plant_exterior_HGSS.png'),
    (24L, 'Route 9', 'rattata Spearow ekans sandshrew nidoran(m) nidoran(f) nidorino nidorina raticate fearow', '/assets/locations/Route_9_HGSS.png'),
    (25L, 'Route 11', 'ekans sandshrew Spearow drowzee pidgey rattata pidgeotto raticate magikarp poliwag goldeen shellder krabby tentacool horsea nidorina dugtrio', '/assets/locations/Route_11_HGSS.png'),
    (26L, 'Route 12', 'oddish bellsprout pidgey venonat gloom weepinbell pidgeotto farfetch''d slowpoke slowbro magikarp poliwag goldeen tentacool krabby horsea seadra snorlax', '/assets/locations/Route_12_HGSS.png'),
    (27L, 'Route 13', 'oddish bellsprout pidgey venonat gloom weepinbell ditto pidgeotto farfetch''d magikarp poliwag goldeen tentacool krabby horsea seadra', '/assets/locations/Route_13_HGSS.png'),
    (28L, 'Route 14', 'oddish bellsprout venonat pidgey ditto pidgeotto gloom weepinbell venomoth', '/assets/locations/Route_14_HGSS.png'),
    (29L, 'Route 15', 'oddish bellsprout venonat pidgey ditto pidgeotto gloom weepinbell venomoth', '/assets/locations/Route_15_HGSS.png'),
    (30L, 'Safari Zone', 'nidoran(m) nidoran(f) exeggcute rhyhorn venonat nidorino nidorina parasect scyther pinsir chansey paras tangela doduo kangskhan cubone tauros marowak venomoth magikarp poliwag goldeen psyduck slowpoke krabby dratini dragonair', '/assets/locations/Pal_Park_HGSS.png'),
    (31L, 'Fuchsia City', 'magikarp poliwag goldeen krabby seaking gyarados', '/assets/locations/Fuchsia_City_HGSS.png'),
    (32L, 'Route 16', 'spearow Rattata doduo raticate fearow snorlax', '/assets/locations/Route_16_HGSS.png'),
    (33L, 'Route 17', 'spearow Rattata doduo fearow ponyta dodrio magikarp poliwag goldeen tentacool krabby shellder', '/assets/locations/Route_17_HGSS.png'),
    (34L, 'Route 18', 'spearow doduo raticate fearow rattata magikarp poliwag goldeen tentacool krabby shellder', '/assets/locations/Route_18_HGSS.png'),
    (35L, 'Route 19', 'tentacool magikarp poliwag goldeen shellder horsea staryu tentacruel', '/assets/locations/Route_19_HGSS.png'),
    (36L, 'Seaform Islands', 'seel horsea krabby shellder staryu slowpoke zubat psyduck golduck slowbro golbat dewgong seadra kingler magikarp poliwag goldeen articuno', '/assets/locations/Seafoam_Islands_B1F_HGSS.png'),
    (37L, 'Route 20', 'tentacool magikarp poliwag goldeen shellder horsea staryu tentacruel', '/assets/locations/Route_20_HGSS.png'),
    (38L, 'Cinnabar Island', 'magikarp poliwag goldeen shellder horsea staryu tentacool omanyte kabuto aerodactyl electrode seel tangelarhydon muk dewgong', '/assets/locations/Cinnabar_Island_HGSS.png'),
    (39L, 'Pokemon Mansion', 'ponyta koffing growlithe vulpix grimer weezing muk rattata raticate magmar ditto', '/assets/locations/Pok%C3%A9mon_Mansion_B1F_FRLG.png'),
    (40L, 'Route 21', 'rattata pidgey pidgeotto raticate tangela tentacool magikarp poliwag goldeen shellder horsea staryu tentacruel', '/assets/locations/Route_21_HGSS.png'),
    (41L, 'Route 22', 'rattata nidoran(m) nidoran(f) spearow mankey magikarp poliwag goldeen poliwhirl', '/assets/locations/Route_22_HGSS.png'),
    (42L, 'Route 23', 'ditto fearow ekans sandshrew spearow arbok sandslash nidorino nidorina mankey primeape magikarp poliwag goldeen slowbro kingler seadra seaking poliwhirl', '/assets/locations/Route_23_FRLG.png'),
    (43L, 'Victory Road', 'onix machop zubat geodude golbat machoke marowak graveler venomoth moltres', '/assets/locations/Victory_Road_1F_HGSS.png'),
    (44L, 'Route 24', 'weedle caterpie oddish bellsprout pidgey kakuna metapod abra venonat pidgeotto magikarp poliwag goldeen psyduck krabby seaking charmander', '/assets/locations/Route_24_HGSS.png'),
    (45L, 'Route 25', 'weedle caterpie oddish bellsprout kakuna metapod pidgey abra venonat pidgeotto magikarp poliwag goldeen psyduck krabby kingler', '/assets/locations/Route_25_HGSS.png'),
    (46L, 'Lavender Town', '', '/assets/locations/Lavender_Town_HGSS.png'),
    (47L, 'Pewter City', '','/assets/locations/Pewter_City_HGSS.png');
